version: '3.3'

services:
  dashboard-frontend:
    container_name: dashboard-frontend
    build:
      context: ..
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ../:/root/dashboard
    environment:
      NODE_ENV: production
      API_HOST: ${API_HOST:-http://localhost}
      API_PORT: 18080
      venus912_DASHBOARD_FRONTEND_PORT: ${venus912_DASHBOARD_FRONTEND_PORT:-8080}
    command:
      - /bin/bash
      - -c
      - "cd frontend && yarn install && yarn run build && yarn run start:prod"
    depends_on:
      - dashboard-backend
    ports:
      - "${venus912_DASHBOARD_FRONTEND_PORT:-8080}:${venus912_DASHBOARD_FRONTEND_PORT:-8080}"
    restart: always
  dashboard-backend:
    container_name: dashboard-backend
    build:
      context: ..
      dockerfile: ./venus912_dashboard/Dockerfile
    volumes:
      - ../:/root/dashboard
    environment:
      FLASK_DEBUG: "False"
      PYTHONIOENCODING: "utf-8"
    command:
      - /bin/bash
      - -c
      - "pip install -r requirements.txt && pip install -e . && cd venus912_dashboard && (venus912_dashboard db init --settings settings.yml || true) && (venus912_dashboard db migrate --settings settings.yml || true) && venus912_dashboard server --settings settings.yml"
    ports:
      - "18080:18080"
    restart: always
